### ISSUE TITLE
hi, I'm new to all this and could do with a little help around the google API integration

### ISSUE THREAD

**Issue by eversonl** [ishaigor/alexa-skill-demo#1]
I'm not sure i have everything set correctly re: keys as I keep getting the response 'the google api service is experiencing a problem, please try again later'

from the log it looks like I dont have the permissions required
{
 "error": {
  "errors": [
   {
    "domain": "calendar",
    "reason": "insufficientRightsForApiAccess",
    "message": "The requested data is not available."
   }
  ],
  "code": 403,
  "message": "The requested data is not available."
 }
}

account is linked and I have added additional scopes to try and get this working

```
Google Calendar
```

View your calendars
Manage your calendars
    Google Contacts
View your contacts
    Google+
Know your age range and language
    Basic account info
View your basic profile info
Additional access
View your approximate age
View your language preferences

the API key is being passed in the request (looking in the cloud log I can see it)

**Comment by ishaigor** [comment]
Hi Lee,
Did you set-up Google API for the skill as described in README? https://github.com/ishaigor/alexa-skill-demo#google-api-project-setup
Also, this will work only on real device after one asks Alexa for the help with the skill and links Amazon account to google one. Open companion app in the browser http://alexa.amazon.com/spa/index.html#cards, ask for help, click the link. You can also use companion app on your TV/phone.
Please follow all the steps in the README as skipping a step results in non-working skill.
Testing will not work
Irena

**Comment by eversonl** [comment]
Picking this apart (and I am no developer) I dont see where the token is getting populated in the index.js. this could be why the log is suggesting "Authorization:Bearer undefined" 
Line 471 of index js feeds in the token but I dont see anything populating it. 

Again apologies, this is something I am trying to learn

**Comment by ishaigor** [comment]
@eversonl, this particular example is for Alexa Skill - it has to be setup and configured all the way for Authorization Code Grant (OAuth 2.0) to work - as outlined in the README. It will not work with the Service Simulator for the skill. And the token will only be populated on the device. If you are just interested in the OAuth 2.0 - this is not complete sample for you to use. Read https://developers.google.com/identity/protocols/OAuth2 for further details.
